### ISSUE TITLE
openlab package fresh install behavior

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#123]
Hi @r-a-y - Feel free to ignore/close if this is not intended to be working yet. Some weird behavior during installation of openlab package on a fresh, non-MS WP install:

- Plugin installer tries to install BP six times. It only works the first time :)
- Clicking the "go to CBOX plugins page" link at the end of installation fails. I think the admin page is not being registered because...
- after install, the CBOX main dashboard page says "Before you can use... we'll need to install BuddyPress"; clicking Continue takes me to a page where it says it's activating plugins, but then sends me back to the same message.

The install process is successfully downloading BP, but it (and its dependent plugins) are not being activated.

**Comment by r-a-y** [comment]
Groan.  I think during a recent commit to get dependencies working for 
non-installed plugins (BP Event Organiser requires Event Organiser), I 
broke the initial install process.

I'll fix this up later tonight.

**Comment by boonebgorges** [comment]
No rush - I wasn't really sure whether I should even be going all the way through the installation process in the prototype :-D

**Comment by r-a-y** [comment]
Okay, so the main issue was I didn't test single-site sufficiently :)

`activate_plugin()` doesn't work on single-site if you set `$network_wide` to true, which is what I was doing.  This is now fixed in commit a56f40b.

The second issue with the "Return to the CBOX plugins page" button showing up is wrong, it should show the "Return to CBOX dashboard" button in this instance.  This is now fixed in commit 5a18420.  I think it probably makes sense to backport this commit to `1.0.x` branch as well.

You should now be able to test the install process again without any weird stuff happening!
