### ISSUE TITLE
Change all subpackage textdomains to 'commons-in-a-box'?

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#148]
Related: #114 

Currently, our "subpackages" - cbox-theme, openlab-theme, cbox-openlab-core - have their own textdomains. This is problematic in terms of integrating with wordpress.org translation systems.

I'd like to suggest that we switch all of these subpackages so that they have the textdomain 'commons-in-a-box'. @r-a-y Does this seem OK to you?

**Comment by r-a-y** [comment]
Hmm, I'm not sure how changing the textdomains for these plugins and themes to `commons-in-a-box` will make things any easier for translation on wordpress.org, but you have more experience than I do with l18n and wordpress.org, so I trust your judgment!

**Comment by boonebgorges** [comment]
We only distribute a single plugin in the wordpress.org repo, and I believe that their infrastructure sets up a single GlotPress project per plugin/theme. As such, translation calls to 'openlab-theme' etc will not be imported to a GlotPress project, and won't be translatable on wordpress.org.

I'm going to make the change.

**Comment by r-a-y** [comment]
I'm not sure that's how things work.

Like we install the `openlab-theme` externally from Github, how would that be caught by GlotPress even if the textdomain uses `commons-in-a-box`?  The only way I see this working is if we include a PHP file in CBOX with all the strings for each subpackage... but that sounds like a workaround.

**Comment by christianwach** [comment]
Chiming in to say that I've never quite understood why CBOX includes the theme(s) as zip files when there is [`register_theme_directory()`](https://developer.wordpress.org/reference/functions/register_theme_directory/) available. CommentPress uses that to [register its themes](https://github.com/IFBook/commentpress-core/blob/54e14bd7197432280cfde129b510aeacb42e1d69/commentpress-core.php#L364-L386) which all then share the `commentpress-core` text domain. Seems to have worked thus far. I don't think the caveats apply since CBOX is always network-activated in Multisite.

**Comment by christianwach** [comment]
@boonebgorges What I mean is that the theme(s) can be made available *without* installing them - i.e. registering a theme directory would automatically make them available in the list of themes when CBOX is activated. The other bonus is that, because they are distributed in their unzipped state, the text domain can be applied to the theme(s) and the strings will be picked up by GlotPress.

**Comment by boonebgorges** [comment]
Yes, I'm aware that it can work like that. But I believe that the reason the system was set up as it is, is that the current setup treats plugins and themes exactly the same, and using the same infrastructure and interface for both. I think there's an argument for packaging themes in the way you suggest, but it will break the parallel structure between themes and plugins (since there'll be no "installing" or "updating" for themes).

**Comment by christianwach** [comment]
Well, at least I understand why CBOX does what it does now 👍

**Comment by boonebgorges** [comment]
Flagging as a related issue: openlab-theme, cbox-theme, and cbox-openlab-core don't currently ship with .pot files. See https://commonsinabox.org/groups/openlab-help-support/forum/topic/bp-group-document-plugins-freeze-installation-white-screen/. I'm slightly wary of fixing this before deciding on the long-term strategy - I don't want to introduce .pot files only to swap the textdomain a few releases later.

**Comment by r-a-y** [comment]
I think the purpose of this ticket is to allow users to easily translate our bundled plugins.

Since translate.wordpress.org would require us to release all our plugins and themes under wordpress.org in order to use their translation functionality, this might not fit our development strategy.

Might I suggest another idea?  Let's continue using .pot files, but use another online translation site so users can contribute translations.  Crowdin and Transifex are some popular examples.

Ben Balter does something similar with his WP Document Revisions plugin:
https://github.com/benbalter/wp-document-revisions
https://crowdin.com/project/wordpress-document-revisions

If this sounds like a decent idea, maybe we could think about creating a Crowdin plugin to pull translations that integrates with WordPress core.  Just spitballing here.

**Comment by boonebgorges** [comment]
Thanks for thinking about this, @r-a-y ! I didn't know about Crowdin.

I like the idea of maintaining some flexibility with respect to wordpress.org. On the flip side, I worry about two things. One, by putting ourselves outside of wordpress.org, we decrease the (already low) likelihood that we'll actually find translators for our strings. Two, it's one more integration for us to maintain.

In the spirit of spitballing, I wonder if we should revisit your idea from https://github.com/cuny-academic-commons/commons-in-a-box/issues/148#issuecomment-431959258 about dumping all subpackage strings into a dummy file. The way that I read the translation tools on wordpress.org (see https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/plugins/wporg-gp-plugin-directory/inc/cli and the corresponding calls in https://github.com/GlotPress/GlotPress-WP/tree/develop/gp-includes) I think all that wordpress.org cares about is what you have in your .pot file - not what strings are available in the PHP files. That said, if we dump into a dummy PHP file, all of our bases will be covered. And that way, all we'd have to do is write a script that crawls the subprojects and generates the dummy file. See https://github.com/wp-cli/i18n-command/blob/master/src/MakePotCommand.php#L511 for some prior art.

**Comment by r-a-y** [comment]
@boonebgorges - Do you think `cbox-theme` should be added to the `cbox-strings` plugin? If so, we'd need to swap out the textdomains in `cbox-theme` for `commons-in-a-box` as well.

**Comment by boonebgorges** [comment]
@r-a-y I thought about that, but I got worried that people might be using a custom cbox-theme pot file, and changing the textdomain on existing strings would break it. (This risk seems much less on `openlab-theme` and `cbox-openlab-core`, since they're much younger.) 

As I write this, though, it's starting to feel smart to roll `cbox-theme` into `cbox-strings`, and just include a notice in the changelog that custom translations will have to be moved to the `commons-in-a-box` textdomain.

Do you have an opinion about it?
