### ISSUE TITLE
Feature Request: Allow users to change default avatar

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#158]
This is a feature request from a user who would like to be able to upload a custom default avatar to replace the default CBOX OpenLab avatar.

**Comment by boonebgorges** [comment]
I've tagged this as OpenLab but it's possible that it could be a more general fix, since I think we filter the BP default avatar throughout. CCing @r-a-y

**Comment by r-a-y** [comment]
The Classic package does not alter the BuddyPress default avatar.

If we wanted to implement this feature for both Classic and OpenLab packages, we would need to add a settings field to the settings page for those respective packages.

Another alternative is since this is a BuddyPress feature request, it could be possible to build this out as a plugin for BP instead and add the option under the BP settings page.

**Comment by boonebgorges** [comment]
Thanks for the sanity check, @r-a-y ! I agree that a CBOX-only solution probably doesn't make a ton of sense. A standalone BP plugin might be doable - let's see how resources shake out in the medium term.

**Comment by boonebgorges** [comment]
We have a request from the OL folks to get this in sooner rather than later. We'll build it as CBOX-OL-specific for now, but I'll try to think about building it in such a way that it could be offered to BuddyPress as an enhancement at some point.

**Comment by boonebgorges** [comment]
I've put the interface in the Customizer, under Logos, which is also where you can change the default header logo.

![Screenshot_2023-06-06_06-57-06](https://github.com/cuny-academic-commons/commons-in-a-box/assets/246627/005cb757-c38f-43e6-9d1b-ceb6c1739c84)

**Comment by bree-z** [comment]
This looks good, thanks!
