### ISSUE TITLE
Block editor top toolbar obscured by WP toolbar

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#173]
Hi Boone, 

When using the block editor, the top toolbar with the publish button is obscured by the grey WP toolbar.  It's workable but is a clunky user experience.  I think that intuitively users will want to scroll up to see it, but they have to scroll down.  I also couldn't scroll using the mouse wheel in Chrome, but had to click and drag to scroll.  I could use the wheel in Firefox.  

Not sure I'm describing this well, so I tried to annotate some screenshots.  Thanks!

![toolbarobscured](https://user-images.githubusercontent.com/7189824/52282506-8fd75880-292e-11e9-9c5d-e5ab59bb767c.png)

![toolbarscroll](https://user-images.githubusercontent.com/7189824/52282507-8fd75880-292e-11e9-9616-a3fa9d1d3d59.png)

**Comment by boonebgorges** [comment]
Thanks for the detailed report, @bree-z 

Our ability to do in-depth fixes here is limited. One, because the Block Editor is complex and doesn't like to be moved around. Two, because the OL toolbar is quite finicky and already has lots of duct tape holding it together. (Previously: https://github.com/cuny-academic-commons/openlab-theme/issues/205.)

I've added a bit more duct tape in the form of repositioning when looking at a Block Editor page. It's not ideal in any sense, but it is probably more workable than what you've described above, and is probably all that we can do for now. Please have a look and see what you think.

**Comment by bree-z** [comment]
Thanks, Boone!  This looks good!  It all appears seamless to me.
