### ISSUE TITLE
Difficulty scrolling on main site dashboard

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#175]
When using a small screen, it's very difficult to access any of the items in the left-hand menu of the main site dashboard that require scrolling, e.g. Settings, Tools, etc.  

This only came up as I was testing #174 and trying to get to the Braille plugin settings on the main site while using my 12 inch laptop screen, so I'm not sure if it's related to any of the changes in 1.1.1 or if it's been like this for a while and I haven't noticed because I'm always using my external monitor. 

I had the same experience in Chrome and Firefox.  

It's easier to show than explain, so I made a quick screencast: 

https://drive.google.com/file/d/1fD2cvDGWN8Plgl2kDbuEFjqh_F493Pdl/view?usp=sharing

Thanks!

**Comment by boonebgorges** [comment]
Thanks for the report, @bree-z. This is a duplicate of https://github.com/cuny-academic-commons/openlab-theme/issues/205. I'm going to close that issue in favor of this one, and hopefully we can try to improve the toolbar behavior in a future release. (It'll require a partial rewrite.)

**Comment by r-a-y** [comment]
Boone, I wanted to revisit this a bit because of a user having a hard time viewing all the admin menu items: https://commonsinabox.org/groups/openlab-help-support/forum/topic/help-page-displaying-page-not-found#post-8590

And I think removing the following lines in the `cbox-openlab-core` JS is better than having the admin bar be sticky:

https://github.com/cuny-academic-commons/cbox-openlab-core/blob/2aab2ffa8925ae9a924fbfc4abf3ac15e03f47e5/assets/js/lib/openlab/openlab.nav.js#L507-L513

This makes the admin bar not sticky, but allows the user to properly see all the admin bar menus on the side when scrolling down the page. What do you think?

**Comment by boonebgorges** [comment]
Thanks for looking at this, @r-a-y. I've dug into it a half-dozen times over the past few years and I find it totally baffling each time :)

I took your advice and I agree that it is better than the current behavior, though I was still seeing some funkiness when you'd scroll to the bottom (triggering the `bottom:0; position: fixed` on the menu) and then scroll back to the top. In this case, the first (and sometimes second) menu items would be hidden behind the admin bar, because WP's calculated `top` offset was too low. bf01198 fixes this specific problem by pinning the menu to the top of the parent whenever `position` is `absolute`. But it causes another issue where, if you scroll to the point where position is fixed, then immediately when you begin scrolling up, the left-hand menu jerks to the very top. This is especially jarring when you're on a long page, because the menu might be pulled totally off-screen, and you'll only find it if you continue to scroll. I don't know how to fix this, but IMO it's better than the alternatives.

@r-a-y Could you pull this change and play with it to see if you're seeing the same thing? I'd like your opinion on whether it's a decent compromise.

**Comment by r-a-y** [comment]
@boonebgorges - I tested out the change and it works much better than before!

I noticed a few other things:
- There is a deadzone if your screen width is between 768px and 782px. When this happens, the admin menu cannot be viewed or toggled. Kind of an edge case because I doubt anyone is using a screen size between these widths, but I note it here :)
- If you overscroll all the way to the bottom of the page, the admin menu will become fixed with `style="position: fixed; bottom: 0px;"` and the fixed position will not be removed unless you refresh the page. It looks like this is set by WP in `/wp-admin/js/common.js` here:  https://github.com/WordPress/WordPress/blob/85b28a939f26f259de94f00b50d5d09bb166cb24/wp-admin/js/common.js#L1431-L1442. We can workaround this by amending the `scroll.pin-menu` listener block to remove the `fixed` position:

```
	$( document ).on(
		'scroll.pin-menu',
		function() {
			setTimeout(
				function() {
					if ( 'absolute' === $adminmenuwrap.css( 'position' ) ) {
						$adminmenuwrap.css( 'top', 0 );
					// New addition here:
					} else if ( 'fixed' === $adminmenuwrap.css( 'position' ) ) {
						$adminmenuwrap.css( 'top', 0 );
						$adminmenuwrap.css( 'position', 'absolute' );						
					}
				},
				10
			);
		}
	);
```

**Comment by boonebgorges** [comment]
> There is a deadzone if your screen width is between 768px and 782px. When this happens, the admin menu cannot be viewed or toggled. Kind of an edge case because I doubt anyone is using a screen size between these widths, but I note it here :)

I choose not to care about this :-D

> We can workaround this by amending the scroll.pin-menu listener block to remove the fixed position:

Your workaround involves completely disabling fixed positioning for the admin menu. I'd been trying to avoid that. But seeing as I can't figure out a more elegant solution, I guess this is the most consistent. I'm going to go with it.

Here's a mini-braindump, in case anyone ever wants to come back to this:
- WP does a bunch of magic in wp-admin/js/common to determine the menu positioning based on scroll
- This determination depends on the height of `#wptoolbar`. But this is complicated for several reasons. For one, the final height of `#wptoolbar` may not be set by the time the common.js script is initialized. As such, it may cache a value (`height.adminbar`) that doesn't accurately reflect the height that the user sees.
- The larger problem is that the OL styles the toolbar in ways that don't properly cascade. The height of the inner elements is set to something like 49px. WP seems to understand this for the most part. But then a 19px border-bottom is added, and a `:before` pseudo-element is used to generate the black line at the bottom of that border. This is a nifty trick, but it means that WP doesn't understand these elements as being part of the height of `#wptoolbar`. 

A proper fix would probably be to start from scratch with the custom toolbar, reproducing the appearance in a way that doesn't trip up WP's JS so much.

**Comment by boonebgorges** [comment]
@bree-z The latest is ready to test on openlabdev.commonsinabox.org, so you can see the compromise we've struck.

**Comment by bree-z** [comment]
Thanks @boonebgorges and @r-a-y ! 

This looks good to me, in Chrome and Firefox. I can access all parts of the dashboard without a problem and no longer see the previous weird jumpiness.
