### ISSUE TITLE
Filters on group directory pages don't return correct results 

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#191]
Hi Boone, 

I'm not sure if this is a bug or just old groups on openlabdev.commonsinabox.org -- I vaguely remember something like this coming up before, but I couldn't find a ticket or message.  

The filters on group directory pages, don't return the correct results.  For example, on the [Courses](https://openlabdev.commonsinabox.org/groups/type/course/) page, if I [filter](https://openlabdev.commonsinabox.org/groups/type/course/?academic-unit-schools=arts-and-sciences&academic-unit-departments=sociology&term=&group_sequence=active#) for Arts and Sciences > Sociology, I get two Sociology courses, but also English and other departments.  If I add '[Fall 2018](https://openlabdev.commonsinabox.org/groups/type/course/?academic-unit-schools=arts-and-sciences&academic-unit-departments=sociology&term=Fall+2018&group_sequence=active#)' to the filter, I do get the correct results.  

Thanks!

Arts and Sciences > Sociology

<img width="1153" alt="Screen Shot 2019-08-20 at 12 27 47 PM" src="https://user-images.githubusercontent.com/7189824/63365843-6ddf7980-c346-11e9-9a0a-e4184e4f3f80.png">

Arts and Sciences > Sociology > Fall 2018

<img width="1216" alt="Screen Shot 2019-08-20 at 12 30 13 PM" src="https://user-images.githubusercontent.com/7189824/63365878-8485d080-c346-11e9-8934-50f874f4132a.png">

**Comment by boonebgorges** [comment]
The root problem here is that the Academic Unit filters use `OR` logic, not `AND`. This was an oversight during original development and testing.

I just pushed up some changes to openlabdev.commonsinabox.org that should address this. The changes are not trivial. If you've got time to do some relatively thorough testing of the Member and Group filters - make sure the various combinations still work as expected - we can squeeze this into 1.1.2. Otherwise we'll have to wait for the next release.

**Comment by bree-z** [comment]
Thanks so much Boone!

I tested this pretty thoroughly for all group types and members, and everything was working as expected.
