### ISSUE TITLE
Member Portfolios Widget: Portfolio links listed as "ePortfolios"

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#192]
Hi Boone, 

I'm sure this is something we failed to catch in previous rounds of testing, but when the Member Portfolios widget is added to the sidebar of a Group Home page, the links to the member portfolios are listed as ePortfolios, e.g. "Test Faculty's ePortfolio," no matter what Portfolios are called.

See, for example: https://openlabdev.commonsinabox.org/groups/eng-1101-comd-1100-research-project/

<img width="318" alt="Screen Shot 2019-08-22 at 12 19 32 PM" src="https://user-images.githubusercontent.com/7189824/63531886-829f4700-c4d7-11e9-8167-b43402ef02ae.png">

Thanks!

**Comment by boonebgorges** [comment]
Thanks, @bree-z. At a glance, I think it's going to be hard to fix this and keep the UI as-is. Since 'Portfolio' is a configurable term, we can't simply do a swap of the form `sprintf( '%s's %s', $user_name, $portfolio_label )` - it won't work in many languages. We could try defining an admin-provided string as we do in many other cases, but it would need to have a placeholder - something we don't do with any other strings - and we'd need to somehow enforce a certain format for the custom string, to avoid problems with the wildcard replacement.

Two possible fixes that are much more straightforward:
1. Instead of '{user}'s Portfolio', just have the user's display name.
2. Instead of '{user}'s Portfolio', use the actual title of the linked group, which will have been provided by the individual member.

cc @jennaspevack

**Comment by boonebgorges** [comment]
@jennaspevack @bree-z Any thoughts about my options 1 and 2 above? 2 is elegant because it respects the titles that people have chosen for their portfolios. But it also introduces the possibility that names will be opaque or too long, a problem avoided simply using display names of the users.

@Mamaduka Could you take care of this once a decision's been made?

**Comment by jennaspevack** [comment]
@boonebgorges 2. could have some display issues unless we limit the characters. Is it possible to restrict the characters to one line with "..."? If not, then I'd say 1. @bree-z any thoughts?

**Comment by boonebgorges** [comment]
> Is it possible to restrict the characters to one line with "..."?

Not reliably, since we can't predict things like character size that may cause spillage into a second line. Also, there may be cases where someone's portfolio name is "The Wonderful Portfolio of Jenna" or whatever and the important information will be truncated. A possible design choice for showing the entire things is a hanging indent or something similar, but if that doesn't work then I guess 1 is the best option.

**Comment by jennaspevack** [comment]
Got it. I think 1. using the display name is fine because hopefully the heading will indicate that the things in this list are portfolios or eportfolios or whatever.

**Comment by boonebgorges** [comment]
Sounds good to me. Thanks, Jenna!

**Comment by boonebgorges** [comment]
@Mamaduka I believe this is ready for implementation.

**Comment by Mamaduka** [comment]
@boonebgorges pushed updated.

Didn't create PR, since this was a small modification.

Screenshot:
![Screenshot-7fp4j](https://user-images.githubusercontent.com/240569/87672951-cbfa2400-c784-11ea-9ccb-baaf268637dc.jpg)

**Comment by boonebgorges** [comment]
Excellent, thanks!

**Comment by bree-z** [comment]
This looks good, thanks!
