### ISSUE TITLE
cbox_is_updated() logic can result in dead-end in some cases

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#222]
Hi @r-a-y  - I've just run across the following scenario two times, once on my local and then once on https://openlabdev.commonsinabox.org/wp-admin/admin.php?page=cbox:

1. I was on the 1.1.x branch of commons-in-a-box
2. I switched to the 1.2.x branch
3. When visiting /wp-admin/admin.php?page=cbox, I see the following:
![Screenshot_2020-05-17_22-15-25](https://user-images.githubusercontent.com/246627/82171086-ecdcf080-988b-11ea-8992-bdc0afd32f2e.png)

`cbox_is_updated()` is returning true, but this means that `CBox_Admin::steps()` is bailing, which feels wrong (I think?). On my local machine, I was able to do a bit of poking around and it started working again. On openlabdev.commonsinabox.org, I left it in place so that you could maybe have a look. (I think you should have access on ldv2.)

Perhaps related to 1dc3364715371e37725c4b2a805296ef6b728c6c ?

**Comment by r-a-y** [comment]
Thanks for looking into this, @boonebgorges.

You are right. This is due to the changes in #217, which isn't completely finished yet, so thanks for the debug steps.

Was able to duplicate this locally. Should be fixed in commit 0136765.

I tested on openlabdev, but since openlabdev is under version control, it is having problems upgrading files. I believe you use wp-cli on openlab. If so, I'll need to tweak the `wp cbox update` routine so it installs missing required plugins. It's on my todo list for #217.

**Comment by boonebgorges** [comment]
Thanks for having a look so quickly, @r-a-y ! I can confirm that this allows me to continue with updates.

I never have a clear idea about how to fix the server setup on Commons servers, but for now I have modified the facl settings enough so that I was able to continue with the openlab-portfolio installation. So no huge rush on modifying `wp cbox update`, though of course it'd be nice to have.
