### ISSUE TITLE
Add Creative Commons widget

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#229]
We'd like to add the Creative Commons widget that was customized for the City Tech OpenLab to CBOX OpenLab. 

Tickets:
http://redmine.citytech.cuny.edu/issues/2440
http://redmine.citytech.cuny.edu/issues/2642

Thanks!

**Comment by bree-z** [comment]
Sorry, Boone. I totally missed this one. 

Thank you for raising these concerns. It's definitely international, though Eurocentric and English language-centric.  

I'm not sure if it's too late for inclusion in this release, but we'd like to go ahead with it.  And if it is possible, would the approach (widget vs. optional plugin) make a difference? 

Thanks!

**Comment by boonebgorges** [comment]
It's too late to do this now, but perhaps we can do it in the next minor release.

**Comment by beckej13820** [comment]
@boonebgorges One of the issues you raised here was if it is appropriate to push the same license to all pages/sites. On my campus, one of the things we are trying to teach students is managing their intellectual property and licensing. 

To that point, we don't tell students how to license their work, but teach them about the licenses and let them choose whether to keep a closed license or which creative commons open license to choose. We'd appreciate flexibility instead of hardcoded options.

**Comment by boonebgorges** [comment]
@beckej13820 Thanks very much for providing this point of view. I think we'd definitely want to build this in such a way that we don't force any specific license - CC or otherwise - on any specific site. Users should have to opt to any license, either by manually adding the widget (and accepting the defaults) or being forced to select a license (where the default is a 'null' option).

The question about hardcoding licenses above, however, is not about forcing a *specific* license on anyone. Instead, the question is whether the *available licenses* can be hardcoded. CC licenses in particular are designed around US-centric copyright restrictions, so they may not be applicable in certain jurisdictions. And administrators of an installation may decide that they want to remove certain licenses from the list (like, maybe there are issues that prevent them from offering NC licenses) or even add others that we haven't thought of. 

The set of licenses we're currently working with on the City Tech OpenLab is the CC licenses listed at https://creativecommons.org/licenses/, as well as "regular" copyright and public domain (CC0). CBOX can certainly make this list of licenses filterable by a secondary plugin. But the main question is whether this is sufficient for inclusion in CBOX. Or perhaps the feature is only usable/useful if there's an administrative tool where the network administrator can modify the license list.

**Comment by beckej13820** [comment]
When you look at what the Wordpress Creative Commons Widget claims it can do, it is a good feature list.

At a glance, with the WP CC Plugin you can:

- License your site with a default license
- Display the default license in the footer or as a widget
- Display a license for the entire site, or for individual posts and pages
- License your WordPress Network (WordPress Multisite install)
- License some posts, pages, or images differently from your default license
- License posts and pages by simply including CC Gutenberg blocks for each license required

That being said, I have the official creative commons widget installed on our OpenLab, and you cannot modify the settings on the network level and set a default license. While I respect the fact that you want to make it easy to add additional licenses, I think that the easiest and most sustainable way to do that in OpenLab would be to add 2 additional licenses to what the Creative Commons has.

1. All Rights Reserved
2. Other License: with the ability for the student to copy in License name, terms, and link to deed.

That's what we do with Lumen Learning's OER systems in SUNY, sometimes we have to use the MIT License, Pixabay License, YouTube License, it's rare, but it gives us the ability to accommodate any outliers. Is it true that Creative Commons is still US-centric? I thought that part of the upgrade to 3.0 to 4.0 is that they were updated to be international licenses.

It would be awesome for us if the license could be put in the network-wide footer in a way that we could set a default setting, but that each sub-site could override that for their content on the network, perhaps from the site settings.

**Comment by boonebgorges** [comment]
Thanks to all for your thoughts. For the time being, I've done a straight port of the widget as it appears on the OpenLab. We could consider adding new features down the road if there is demand and if we have the resources.

**Comment by bree-z** [comment]
Thanks, Boone! This looks good, except for one small thing:

Could we move the "Learn more" link up to the same line as the sentence before it?

<img width="351" alt="CCwidget" src="https://user-images.githubusercontent.com/7189824/126050025-09ff684e-4e80-413b-acb6-4f36159bc5a8.png">

And how do superadmins activate this on the network? I didn't see it in the CBOX OpenLab plugins, or in the network admin Dashboard plugins page.

Thanks!

**Comment by boonebgorges** [comment]
> Could we move the "Learn more" link up to the same line as the sentence before it?

I've made this change.

> And how do superadmins activate this on the network? I didn't see it in the CBOX OpenLab plugins, or in the network admin Dashboard plugins page.

They don't. It's available everywhere automatically, with no toggle. This is also how the 'Cloneable' and 'ShareableContent' widgets work. If you need a toggle, then we'll need to think about what makes the most sense - a CBOX-OL-specific toggle, breaking out into a standalone plugin, etc.

**Comment by beckej13820** [comment]
I'd like to suggest that where the CC License is named should also be a clickable link to the license deed. 

https://wiki.creativecommons.org/wiki/best_practices_for_attribution

**Comment by bree-z** [comment]
Thanks Boone! 

> It's available everywhere automatically, with no toggle. 

I think this is fine, thanks!

> I'd like to suggest that where the CC License is named should also be a clickable link to the license deed.

Thanks for the suggestion, @beckej13820! I thought there was a reason we weren't able to do this, but perhaps I'm misremembering. @boonebgorges I agree that this would be ideal - is it possible to link to the license name rather than adding "Learn more"? If not, the "Learn more" text placement looks good, and we can go ahead and close this.

Thanks!

**Comment by boonebgorges** [comment]
We may need to make an adjustment to the wording in order to make this work. If we link the entire phrase 'Creative Commons Attribution (CC BY) license', then we need to account for the possibility of declension in various languages, which is difficult to do when a phrase/sentence is only partially linked. A more straightforward format for the purposes of localization is: `Unless otherwise noted, this site by %s has the following license: [license link]`. Is this acceptable? If not, I think we should leave a separate Learn More sentence.

**Comment by beckej13820** [comment]
Here are some examples of standard language from Creative Commons:

The Creative Commons License Generator uses this language: 

![Screen Shot 2021-07-20 at 2 41 24 PM](https://user-images.githubusercontent.com/29982981/126378093-e819a000-ed26-4614-877b-10be27ed8906.png)

https://creativecommons.org/choose/

The creative commons generator is a good link to review when doing this, because it also has the official HTML markup to make the creative commons license machine-readable, so search engines like google will show the page when someone searches for openly licensed material. I think the most important part is the rel=license on the links.

The wiki I shared also has several alternative variations of wording, and is created by creative commons to give sample and acceptable language. 

![Screen Shot 2021-07-20 at 2 45 39 PM](https://user-images.githubusercontent.com/29982981/126378580-06548fe9-9547-454c-a66b-031408d75ba5.png)

**Comment by boonebgorges** [comment]
Thanks, @beckej13820. The Russian example (only inflected language I know, sorry!) is illustrative of the problem https://creativecommons.org/choose/?lang=ru. In the following phrase:

> Это произведение доступно по лицензии Creative Commons «Attribution» («Атрибуция») 4.0 Всемирная.

The link begins with the word 'лицензии', which is declined. It's not easy to build this markup in such a way that will make it possible to translate into arbitrary languages. As such, I suggest that the linked section remain grammatically distinct, as it is in the 'Selected License' example from CC.

@bree-z I'd like your feedback on the direction we should move.

**Comment by bree-z** [comment]
Sorry for the delay - I reached out for advice to some of the CUNY librarians who know this stuff much better than I do! Can we go with the following:

Except where otherwise noted, this site by [user display name] is distributed under the following license: [license name, linked to license description].

Thanks!

**Comment by boonebgorges** [comment]
Thanks, Bree. This language looks good to me. I've made the change.

**Comment by bree-z** [comment]
Thanks Boone, this looks good!
