### ISSUE TITLE
Open Lab Site Wide header- icons break on subdomain installs on Chrome and Firefox

### ISSUE THREAD

**Issue by beckej13820** [cuny-academic-commons/commons-in-a-box#243]
On a fresh Commons in a Box OpenLab install on Wordpress 5.4 using subdomains, the font awesome icons in the header break on both Google Chrome and Mozilla Firefox, but appear correctly on Safari.

Screenshot of Google Chrome:
![Screen Shot 2020-07-29 at 8 39 16 AM](https://user-images.githubusercontent.com/29982981/88801002-009faf80-d177-11ea-9ddd-8b3a6a54649f.png)
Screenshot of Mozilla Firefox:
![Screen Shot 2020-07-29 at 8 40 00 AM](https://user-images.githubusercontent.com/29982981/88801065-1b722400-d177-11ea-82f9-6e92788a0452.png)
Screenshot of Safari:
![Screen Shot 2020-07-29 at 8 41 01 AM](https://user-images.githubusercontent.com/29982981/88801144-3fce0080-d177-11ea-87ef-7a2f328a0b76.png)

The Commons in a Box site that I am showing is oneonta.sunycreate.cloud with the open portfolio ed-beck.oneonta.sunycreate.cloud

**Comment by boonebgorges** [comment]
Hello @beckej13820 and thanks for the detailed report and screenshots. I was able to reproduce on a subdomain installation. The issue is that browsers' default security configuration forbids loading stylesheets from across domains, and Chrome and Firefox in this case are interpreting the subdomain as a different domain from the parent site. I've made a change that will prevent this problem, by ensuring that the font-awesome stylesheet is loaded from the current site's URL.
