### ISSUE TITLE
Allow users with no OpenLab member type to choose a member type on the settings page

### ISSUE THREAD

**Issue by beckej13820** [cuny-academic-commons/commons-in-a-box#245]
This is a feature request:

### Feature Description

It would be nice if either:

- There was a default member type for users when they are first created, OR
- Existing wordpress users without a member type could select a member type.

### Feature Use Case
The use case for this would be any university that wishes to connect OpenLab to their SSO, instead of using the WordPress Registration features. Most commonly used SSO plugins like the WP Shibboleth or WP OneLogin SSO can be set up so that new users are generated on the first login. However this would bypass the registration page where new users would typically indicate if they are a Student, Staff, or Faculty member.

### What happens now
What happens to these users currently is they have no member type, but they also are not allowed to select a new member type at site.url/members/me/profile/edit (This is true, even if there are no sign up codes that limit a member types availability)

What ends up happening is these users end up with no user type and no way to get one without administrator intervention.

### What I would like to happen
My ideal scenario for this would be to replace every "Sign Up" link with a link to mysite.url/members/me/profile/edit on my openlab child theme.

When a student clicked on the custom sign up for the first time, they would be directed to my university SSO and after authentication, they would arrive at their settings screen where they can fill in or edit their Display name, any other required profile fields, and select their member type.

**Comment by boonebgorges** [comment]
Hi @beckej13820 - Thanks for the carefully explained request.

In theory, it would be nice if you could set the member type programmatically, using data from your SSO or identity provider. They may already have information about who's a student, faculty, etc. 

But in the absence of this, I agree it's a good idea to have a better way to deal with accounts that don't have a member type. We currently have two different restrictions on member type selection: (a) certain members types can only be selected at registration by users who have the proper signup code (you reference this above), and (b) administrators can restrict *changes* in member type, so that (for example) Students may change to Alumni but not Staff or Faculty, while Staff may change to Faculty but not Student. Thus I can imagine allowing users with no member type to select any type that is not restricted by signup code (ie respecting restriction (a)) but otherwise allowing any type to be selected (ie ignoring (b), since there's no "source" member type). 

Does that seem reasonable to you?

Changing the 'Sign Up' link is something you could easily do yourself by using the `bp_get_signup_page` filter. I don't think this is something we'd want to create a UI for in CBOX itself.

**Comment by beckej13820** [comment]
@boonebgorges 

Thank you for your response. Everything above seems reasonable. If a user type has no restrictions/no signup codes, then a new user should be able to select that group type from "profile edit" page. If there are restrictions or there is a signup code, then a user without a group type should not be able to select that user type. 

I agree with your assessment that changing the link should be my responsibility, and not needed within the UI for CBOX.

**Comment by boonebgorges** [comment]
Excellent. I've made the change in 0e10972. When editing their profiles, users with no member types will be allowed to select any member type that's not protected by signup code. This will be part of the 1.2.0 release in a few weeks.
