### ISSUE TITLE
Project and club cloning, step 2: 'Create site' checkbox is always unchecked

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#256]
In the second step of project and club cloning, the checkbox for 'Create a site' is never checked, even if the source group has a site. 

If I do not check the box to set up a site, no site is created for the clone.  E.g.:

Source: https://openlabdev.commonsinabox.org/groups/prehistoric-club/
Clone: https://openlabdev.commonsinabox.org/groups/prof-teslas-clone-of-math-club/

**Comment by boonebgorges** [comment]
Previously, the 'Set up a site' checkbox was prechecked if we determined that the group *type* had the box checked by default. This is true for courses and portfolios, not for clubs and projects. When opening cloning to clubs and projects, this logic no longer works, and instead we need to look at the specific group being cloned. See #208. This is now ready to test.

**Comment by bree-z** [comment]
Thanks, Boone.  The 'Set up a site' is now checked and the source group site is cloned. 

However, I cloned a project without an associated site, and the box was checked during the cloning process. The cloned site looks like some version of the CBOX OL main site (see link below).

Source: https://openlabdev.commonsinabox.org/groups/hiking-in-the-rhodope-mountains/
Clone: https://openlabdev.commonsinabox.org/groups/hiking-in-the-rhodopes-clone/

Thanks!

**Comment by boonebgorges** [comment]
Thanks, Bree. The logic here has become very complex, so sorry for the false starts. Here's how it now works. On step 2 of group creation, I use the following logic to determine how the 'Associated Site' group should be built:

- If the group is being created via clone, and the clone source has a site, then (a) show the 'Clone' radio button, and (b) precheck the 'Set up a site?' checkbox
- If the group is not being created via clone, then (a) don't show the 'Clone' radio button, and (b) if the group type either requires a site (Portfolios) or has the site enabled by default (Courses), then precheck 'Set up a site?' Otherwise (c) don't precheck 'Set up a site?'

**Comment by bree-z** [comment]
Thanks, Boone! 

Now what I see is that when cloning a project or club without an associated site, the 'Set up a site?' box is checked by default and the 'Create a new site' radio button is selected.  I can uncheck the box and continue with the cloning process. When I do so, no site is created for the cloned group.

The 'Set up a site?' box is also checked by default during project and club creation.

Thanks!

### Cloning a club without a site:

<img width="898" alt="SetUpSiteChecked" src="https://user-images.githubusercontent.com/7189824/89669931-50d0ed00-d8ae-11ea-8bf3-6673c35cfca3.png">

**Comment by boonebgorges** [comment]
I've made yet another change to try address this. Thanks for your patience.

**Comment by bree-z** [comment]
Many thanks Boone! The site creation options look good for group creation and cloning.
