### ISSUE TITLE
Reorder stylesheets in OpenLab Theme

### ISSUE THREAD

**Issue by beckej13820** [cuny-academic-commons/commons-in-a-box#263]
Currently, the color scheme style sheets are taking precedent over customizer "additional CSS" stylesheet. This means that variables set by the color scheme style sheets are very difficult to override.

For example: Toolbar-blue.css and blue.css takes precedence over customizer Additional CSS. If I tried to change the color of the WordPress Admin Bar using additional CSS, it would fail because the toolbar.css would be called last and take over.

![Screen Shot 2020-08-08 at 6 10 57 PM](https://user-images.githubusercontent.com/29982981/89720668-b1d9ed00-d9a2-11ea-852a-645269640875.png)

Reordering the style sheets and putting the additional CSS last would be useful for those of use that want to do a little extra branding of the theme to our institutional colors, but don't want to go through all the work of generating a custom child theme.

**Comment by boonebgorges** [comment]
The issue here is not the load order. If you look at the page source, you can see that the toolbar stylesheets are loaded before the Additional CSS is put into the document. (Search for css/color-schemes in the page source.)

The issue demonstrated in your screenshot is that our toolbar selectors are more specific than yours. CSS specificity says that the selector `.oplb-bs #wpadminbar` will take precedence over `#wpadminbar`. See https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity. Because your custom styles are loaded later, you should be able to use the same selector: `.oplb-bs #wpadminbar`, in this case. Or, a simple trick for overriding most any styles is to put `body` at the front: `body .oplb-bs #wpadminbar`.
