### ISSUE TITLE
Dashboard > Brand Settings 

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#265]
Hi Boone, 

When I go to Dashboard > CBOX OpenLab > Brand Settings > Visual and click Customize, I get the following error message:

<img width="869" alt="Screen Shot 2020-08-09 at 7 17 40 AM" src="https://user-images.githubusercontent.com/7189824/89730916-0e73f100-da11-11ea-9613-f23478312253.png">

Thanks!

**Comment by boonebgorges** [comment]
This was being caused by the cloning widgets just added to the package in the last few days. They assume that every site is associated with a group. But in the case of the main site (and group-type-template sites) there is no corresponding group. I've made a change so that these widgets are no longer registered on sites without a corresponding group.

**Comment by bree-z** [comment]
Thanks, Boone! I'm able to access Brand Settings > Visual.
