### ISSUE TITLE
All groups appearing in group-specific directories

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#282]
Hi Boone, 

A user is [reporting](https://commonsinabox.org/groups/openlab-help-support/forum/topic/openlab-1-2-1-group-type-pages-no-longer-filter/) a bug that I can't reproduce on openlabdev.commonsinabox.org.

It looks like all groups are appearing in his group-specific directories, e.g.: https://oneonta.sunycreate.cloud/groups/type/course/

The group checkbox filters we use on the site-wide search are also appearing in the group directories.

Sorry if I'm missing something obvious, but I'm not sure how this could be a configuration issue. 

Thanks!

**Comment by boonebgorges** [comment]
This might be due to the Search Results page not being generated during upgrade. See https://commonsinabox.org/groups/openlab-help-support/forum/topic/openlab-1-2-1-group-type-pages-no-longer-filter/#post-8499. I'm going to wait for follow-up from the reporter before moving forward with a fix, but it's likely that this will require a fairly quick 1.2.2.

**Comment by boonebgorges** [comment]
I've confirmed that the absence of Search Results is the root of the problem. Somehow it got missed during development that the page needed to be installed during upgrade.

I've written a plugin that can be used to create the page: https://commonsinabox.org/wp-content/uploads/cboxol-fix-brand-pages.zip

I'll write an upgrade routine and release 1.2.2 in the next day or so.

**Comment by boonebgorges** [comment]
I've had a chance to run through the various upgrade scenarios (1.1.x - > 1.2.2 and 1.2.x -> 1.2.2) and it looks like my fix is working properly.
