### ISSUE TITLE
Permalinks issue on new group sites

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#322]
Hi Boone, 

This issue was reported by BMCC (outside of the forum), and apparently it's been an issue for over a year. They said that one WP update a few months back solved it briefly, but the bug returned after the next WP update.

I was able to reproduce this on openlabdev.commonsinabox.org:

- I created a new course with the following course site: https://openlabdev.commonsinabox.org/new-course-winter-2021/
- I published a post, for which I created the category 'Announcements'. 
- I added the Announcements category to the menu. 
- When I visited the category archive page for [Announcements](https://openlabdev.commonsinabox.org/new-course-winter-2021/category/announcements/), I got a 404 error.
- I visited Dashboard > Settings > Permalinks and didn't change anything or even save changes.
- When I went back to the category archive page for Announcements, the post in that category displayed correctly.

Here's an example of a site where I didn't fix the issue: https://openlabdev.commonsinabox.org/new-course-2-winter-2021/category/cats/ 

I also tried flushing permalinks on the course template site, but I still had the same issue with a new site created after doing that: https://openlabdev.commonsinabox.org/new-course-3-winter-2021/category/penguins/ 

Not sure if this is relevant, but after the clicking 'Save' on the permalinks settings page on the template site, I saw a notice at the top of the page saying "You should update your .htaccess file now." I'm also not sure if it was there before I saved, or I just noticed it afterwards.

Thanks!

**Comment by boonebgorges** [comment]
Rewrite rules are flushed at the time of site creation, and we try to ensure that all taxonomies are available at the time of rewrite flushes, so that eg category permalinks work properly. But this doesn't appear to be working for some reason, perhaps due to a secondary plugin that's doing an additional flush_rewrite_rules() call. 

Rather than trying to narrow it down, I've put in a broad fix that does the following: on the first pageload after the site creation (when logged in as a super admin), flush the rewrite rules at the very end of the pageload. In my tests, this fixes the problem. It also fixes it for existing sites, once visited by the logged-in administrator. This is ready to test on openlabdev.commonsinabox.org.

**Comment by bree-z** [comment]
Thanks, Boone! This looks good. 

Does this fix only apply to newly-created sites? If so, I'll let BMCC know that they'll still need to flush permalinks for existing sites where they find the issue.

**Comment by boonebgorges** [comment]
No, it should work for existing sites as well.

**Comment by bree-z** [comment]
Thanks, Boone! I thought I saw a 404 when visiting [this link](https://openlabdev.commonsinabox.org/new-course-2-winter-2021/category/cats/) from above, but after publishing a new post in that category everything looks fine. I checked a few other existing sites, and category archive links all seem to be displaying properly.
