### ISSUE TITLE
Group Moderators can't access Membership page

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#323]
This issue was reported by BMCC, and I was able to reproduce on openlabdev.commonsinabox.org.

When logged in as a moderator of a group, I cannot access the Membership page. When I click Membership, the profile just reloads.  I was testing logged in as the teststudent user in this group: https://openlabdev.commonsinabox.org/groups/plants-are-good/

See, for example:

![ModeratorMembership](https://user-images.githubusercontent.com/7189824/101923096-f8cc2f00-3b9c-11eb-99bc-ea744193a88b.gif)

**Comment by boonebgorges** [comment]
We need to lay out what Moderators ought to be able to do. BP does not allow group mods to do things like manage membership (promotion, banning, etc). Is it OK to inherit these default permissions? If so, then we should simply be able to change the URL for Membership so that it points to the same URL as what regular group members see. If we need them to be able to perform some Administrator-level tasks, then it's more complicated.

**Comment by bree-z** [comment]
We've discussed with BMCC, and have agreed that it's fine to inherit the default permissions and change the URL for Membership so that it points to the same URL as what regular group members see. 

Thanks!

**Comment by boonebgorges** [comment]
Thanks, @bree-z. I've made the change and it's ready to test.

**Comment by bree-z** [comment]
Thanks, Boone! This looks good.
