### ISSUE TITLE
Groups can be cloned by non-admins

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#325]
Hi Boone, 

This was reported by BMCC, and I was able to reproduce on openlabdev.commonsinabox.org. 

Logged in as testfaculty, I was able to clone a group of which I’m only a member, not an admin. Shared cloning was *not* activated for this group, and I’m not able to clone from the group itself, because there’s no cloning link available to me anywhere in the UI.

However, I could clone it by going to My Clubs > Create/Clone, and then choosing it from the dropdown of available groups for cloning. 

On the cloned group home, I see credits listed there as if I had cloned through shared cloning.

Source group: https://openlabdev.commonsinabox.org/groups/political-theory-society/
Cloned group: https://openlabdev.commonsinabox.org/groups/prof-teslas-clone-of-political-theory-club/ 

Thanks!

**Comment by boonebgorges** [comment]
Looks like this was introduced by the refactor in https://github.com/cuny-academic-commons/openlab-theme/commit/b0760b5b99c996e737f87538f1f1921d59a6c77e. Prior to that changeset, the groups in the 'Clone Existing' dropdown were limited to those owned by the user.

> On the cloned group home, I see credits listed there as if I had cloned through shared cloning.

This is not a bug; it's expected behavior that a cloned group would have this section. The bug is that the clone was allowed in the first place.

@Mamaduka In the linked changeset, you swapped `openlab_get_courses_owned_by_user()` with `openlab_get_groups_of_type()`. In the new function, you pass a `user_id` parameter to `groups_get_groups()`, but this checks for *membership*. Perhaps the easiest fix here is to simply add a clause after this query that filters `$groups_of_type` to eliminate those where the current user is not an administrator. (We may also want a more descriptive function name than this.)

In addition to this change to the dropdown UI, we should also introduce some validation to ensure that the user has the right to clone the group. This means a few things. First, when the `?clone=` URL param is passed, we should validate before returning the source info from the AJAX endpoint. Maybe in `openlab_group_clone_fetch_details()`? Second, when submitting the creation form, we should validate that the current user has permission to clone `$_POST['group-to-clone']` (see `openlab_clone_create_form_catcher()`).

Looking at function names, it seems like `openlab_user_can_create_group()` would be a good place to introduce the is-admin logic, but that function really checks group *types*, not specific groups. So perhaps we can introduce a new function that checks whether a specific user can clone a specific group. This function would check everything: whether a group type allows cloning, whether the current user is allowed to create groups of the current type (these two would be `openlab_user_can_create_group()`), then whether the current user either is the admin of the group OR whether 'shared cloning' is enabled for the current group. Then this new function could be used in all three places described above: when building the dropdown, when fetching clone details via AJAX, and when validating form submission.

**Comment by Mamaduka** [comment]
@boonebgorges Improved checks in `openlab_user_can_clone_group()` function.

I think I covered all the cases but another review would be appreciated.

**Comment by boonebgorges** [comment]
Thanks so much, @Mamaduka . I've reviewed the changes and they look pretty good. Passing this along to @bree-z for testing on openlabdev.commonsinabox.org.

**Comment by bree-z** [comment]
Thanks, Boone and George! This looks good.
