### ISSUE TITLE
Transition for Travis CI to Github Actions

### ISSUE THREAD

**Issue by Mamaduka** [cuny-academic-commons/commons-in-a-box#327]
Travis CI's support for the Open Source project has changed lately. This might be a good time to consider transitioning to Github Actions.

**Comment by boonebgorges** [comment]
Yes, great idea. Here's the GH page on migrating. https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions @Mamaduka If you've got the bandwidth to have a first look at this (it'd apply to this package as well as openlab-theme and cbox-openlab-core), feel free to do so. Otherwise I'll have a look in the upcoming weeks.

**Comment by Mamaduka** [comment]
Hi @boonebgorges,

Included some other changes besides migrating to Github actions. If you're okay with changes, I'll move them to other repos.

**Comment by boonebgorges** [comment]
Changes all look good to me. Thank you!

**Comment by Mamaduka** [comment]
Hi @boonebgorges,

Moved `openlab-theme` and `cbox-openlab-core` repost to Github Actions as well.

**Comment by boonebgorges** [comment]
Awesome! https://github.com/cuny-academic-commons/openlab-theme/runs/1724295288?check_suite_focus=true
