### ISSUE TITLE
Extraneous checkboxes appearing in badges admin

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#330]
Hi Boone, 

When I go to the badges admin screen (https://openlabdev.commonsinabox.org/wp-admin/network/admin.php?page=openlab-badges), I see some extra checkboxes that appear beneath group type checkboxes for all badges listed there. 

<img width="1189" alt="BadgesExtraCheckboxes" src="https://user-images.githubusercontent.com/7189824/104965242-4ada4e80-59ac-11eb-9d34-87afc019668d.png">

**Comment by boonebgorges** [comment]
This is a result of a bunch of weird things working together. 

The root is that the openlabdev.commonsinabox.org site somehow got its version of BuddyPress upgraded to 7.1.0. The version that's pinned for the 'openlab' package is 6.3.0. @r-a-y Do you have any idea how this might have happened? (Timestamps on the files show that the plugin was updated on Dec 21 2020.) I know that there have been some recent changes to WordPress to allow plugins to be auto-updated. Is it possible that this happened here? I'm concerned that it will happen on other CBOX installations, which throws a wrench in our ability to block updates until we've vetted them and pinned a new version. 

Or perhaps you @bree-z updated BuddyPress? Or maybe I did? If it was manual, I'm less concerned about it.

In any case, BuddyPress 7.0.0 introduces an interface for managing group types, something like what we have in CBOX-OL. Part of this upgrade appears to include an automatic migration, which creates group types in the database for any group types it finds in the database. So what was happening here is that the openlabdev.commonsinabox.org test installation has a ton of old groups with weird group types, because of all the testing that's taken place. I deleted the extraneous group types and things are now working properly.

I'll open a separate ticket to deal with the broader problem of BP 7.0.0 compatibility.

**Comment by bree-z** [comment]
Thanks, Boone! I no longer see the checkboxes. 

And FWIW, I didn't update BuddyPress.

**Comment by bree-z** [comment]
Since there's a separate ticket for BP 7.0.0 compatibility, I'm going to close this one.
