### ISSUE TITLE
Course Term populates as ‘Spring 2022’

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#331]
When a course is created or cloned, the course term is populated as ‘Spring 2022’. I know it’s designed to provide a value that makes sense for a likely upcoming term, but this seems a little too far off. 

Thanks!

<img width="591" alt="CourseTerm" src="https://user-images.githubusercontent.com/7189824/104965421-ae647c00-59ac-11eb-98f9-7a1cbda22ff5.png">

**Comment by boonebgorges** [comment]
This was a logic error. The intention was that the default Term would be 'Spring' if the current month is between October and March. This was working properly. But I had some logic in place to increment the year, because I was thinking of the case where we're in October 2020 and want to default to Spring 2021. I've made a change so that the behavior splits properly between Oct-Dec and Jan-Mar.

**Comment by bree-z** [comment]
Thanks Boone! This looks good. New courses now default to Spring 2021.
