### ISSUE TITLE
Group Cloning: Only top level academic unit is copied from source

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#361]
Hi Boone,

When I clone a group that has both a School and Department, only the School is copied from the source to the cloned site. In the case of courses, where both units are required, I get an error message and must select a department, but for projects where they're not required, the school is copied, but without the department. See, for example:

Source: https://openlabdev.commonsinabox.org/groups/project-shared-clone/ (School: Arts & Sciences, Dept: Sociology)
Clone: https://openlabdev.commonsinabox.org/groups/political-sociology-project-shared-clone-1/ (School: Arts & Sciences, no dept)

Source: https://openlabdev.commonsinabox.org/groups/summer-2021-course/ (School: Performing Arts, Dept: Composition)
Clone: https://openlabdev.commonsinabox.org/groups/summer-2021-course-shared-clone-1/ (School: Performing Arts, I got an error message during cloning since the dept wasn't pre-selected)

<img width="916" alt="Screen Shot 2021-07-20 at 6 48 06 PM" src="https://user-images.githubusercontent.com/7189824/126419500-73b0eb7d-6f44-41fb-9293-bf2dd1dd3871.png">

Thanks!

**Comment by boonebgorges** [comment]
This is not a new bug, but appears to have existed since openlab-theme was introduced.

For terminological clarity, nothing is "copied" on the group create page; the clone source details are fetched from the server, and then default values based on that source are pre-filled for the new group. In this case, the proper checkboxes were not always being pre-checked.

Should be resolved by a5e931a.

**Comment by bree-z** [comment]
Thanks Boone! This looks good.
