### ISSUE TITLE
Validation for Course Description fails

### ISSUE THREAD

**Issue by arto-a** [cuny-academic-commons/commons-in-a-box#363]
I was testing the following site: https://openlabdev.commonsinabox.org/groups/hegel-and-marx-logical-studies/

Originally, there was a course description entered in the "Description (required)" field. 

I deleted the entered text and clicked "Save Changes". The page updated and reloaded without throwing any errors for the missing course description. 

I have included a screenshot of the empty Description box, following the page update.
![Screenshot from 2021-07-22 14-56-00](https://user-images.githubusercontent.com/68743478/126693827-c8eea455-5682-4bb9-ae50-5dd2cd59cb0a.png)

**Comment by boonebgorges** [comment]
In https://github.com/cuny-academic-commons/openlab-theme/issues/250, we implemented a workaround that allowed form submission with an empty Description field, to avoid the fact that JS `required` validation is more strict regarding whitespace than BP's server-side validation. I've changed this logic so that the clikent-side validation requires a non-empty/whitespace string.

**Comment by arto-a** [comment]
This is now fixed. Thanks!

**Comment by boonebgorges** [comment]
Thanks!
