### ISSUE TITLE
Link to associated site not visible on Group Home when site is private

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#379]
Hi Boone, 

I’m noticing an issue on the CBOX OpenLab Community Hub site, where if I create a group with an associated site set to either 'I would like the site to be visible to community members with a role on the associated site.' or 'I would like my site to be visible only to those members with an administrator role on the associated site.', I’m not able to see the link to the site on the Group Home. If I change the site privacy settings to open or 'I would like the site to be visible only to members of this community.' I’m able to see the site link, but if I change it back to private it disappears again. In all cases, I can access the site and Dashboard via URL, and I’m the site admin in all cases. I’m also not able to see the site link if I’m logged in as a super admin. Here are a few test groups (they’re all hidden):

https://cboxopenlab.org/groups/brees-test-project-1/
https://cboxopenlab.org/groups/project-with-a-private-site-2/
https://cboxopenlab.org/groups/project-with-a-private-site/
https://cboxopenlab.org/groups/brees-test-course-1/

I can’t reproduce this on openlabdev.commonsinabox.org:

https://openlabdev.commonsinabox.org/groups/public-group-with-private-site/
https://openlabdev.commonsinabox.org/groups/hidden-group-with-private-site/

Thanks!

**Comment by boonebgorges** [comment]
Thanks for the detailed ticket. 

The issue is that cboxopenlab.org, unlike the CT OpenLab or openlabdev.commonsinabox, does not use the default `wp_` prefix for database tables. And the way that we check whether the site info should be shown requires using this site prefix to query for a user's capabilities. So on cboxopenlab.org, the query is turning up empty. https://github.com/cuny-academic-commons/cbox-openlab-core/blob/aac385426a3b3a1645870b4b0b1ee0734fbcec74/includes/group-sites.php#L988 

I wanted to be sure that this breach of bad practice is not something I introduced, so I went back and traced it back to the very earliest days of the OpenLab.

I've put a hotfix in place on cboxopenlab.org so you can confirm it's working. Once confirmed, I'll merge here.

**Comment by bree-z** [comment]
Thanks, Boone! This looks good. I see the group site link no matter what the site privacy settings are.
