### ISSUE TITLE
OpenLab Homepage: Logical Tab Order

### ISSUE THREAD

**Issue by beckej13820** [cuny-academic-commons/commons-in-a-box#386]
When using the keyboard to navigate the OpenLab Homepage, there is a jump in the tab order doesn't follow a linear top to bottom, left to right order as you might expect.

When you tab through the page, you first go through the Site Menu, but you skip the WordPress admin menu, entirely, tab through the entire page of content, and only when you have finished all the way through the footer, does it come back up to the WordPress admin menu.

I would expect to go through the main menu, and then continue directly to the WordPress admin bar after.

**Comment by boonebgorges** [comment]
The tab order reflects the order of elements in the DOM. The admin bar is rendered at the very end of the document body, so it's last when you're tabbing through elements. This is an artifact of how WordPress added the toolbar to the front-end (it used to be an admin-only tool). To help keyboard navigators, WP added a "skip to toolbar" link with a low tabindex, to go along with the "skip to login" and "skip to content" links. See https://core.trac.wordpress.org/ticket/21471

I would not recommend that we manually try to fix the tab order. See https://webaim.org/techniques/keyboard/tabindex Instead, we should consider restoring the 'Skip to toolbar' link, which was removed from the City Tech OpenLab in http://redmine.citytech.cuny.edu/issues/1876 and thus never made it to CBOX OpenLab. @bree-z could you chime in here?

**Comment by beckej13820** [comment]
Hi Boone, 

I think I understand your comment. However, if I go to a non-openlab wordpress site as a logged in user, the WordPress Admin is at the very top visually, and first in the tab order right after the "skip to" links. That's what made me think it was an OpenLab issue and not a WordPress issue.

**Comment by boonebgorges** [comment]
It appears that WP made a change in version 5.4 that changed the way that the admin bar is loaded. See https://core.trac.wordpress.org/ticket/50702#comment:1, https://core.trac.wordpress.org/ticket/47053

Instead of reintroducing the 'Skip to toolbar' link, perhaps we could consider implementing the `wp_body_open` hook. I've tested this locally, and what we end up with is that the admin bar is *the first thing* that you tab to, even before the navigation that appears *above* the admin bar in openlab-theme. I'm unsure whether this is an improvement. If we go this route, we may want to consider changing our custom 'Skip to admin bar' link (see https://github.com/cuny-academic-commons/openlab-theme/blob/7f2d689f54899841fcde741a794ec0d5e3883b7c/lib/page-funcs.php#L6=) to 'Skip to main navigation' or something like that.

Looking more closely at the original issue, it appears that http://redmine.citytech.cuny.edu/issues/1876 was meant to do the following:
- If you are logged out, show a 'Skip to login' link
- If you are logged in, show a 'Skip to admin bar' link

This custom link makes WP's native 'Skip to toolbar' link redundant, which is why it's removed via JS by openlab-theme. https://github.com/cuny-academic-commons/cbox-openlab-core/blob/27913ac024f96dd31eac6887423650581e49820f/assets/js/lib/openlab/openlab.nav.js#L182=

It seems like, no matter what we do - status quo, or switching to `wp_body_open` - there's going to be some funniness regarding tab order. So my initial recommendation is to do nothing, and rely on the existing 'Skip to admin bar' behavior. But feedback from the OpenLab team would be helpful on this.

**Comment by beckej13820** [comment]
A third alternative would be to reorder the two rows in the header, and use the current WordPress core behavior, which would make the visual order match the tab order.

I understand that's a design consideration but just wanted it to be on the table as an option. Thank you all.

**Comment by boonebgorges** [comment]
For completeness's sake, a fourth option is to shoehorn the WP admin bar into the DOM so that it matches the arrangement on the page. This is likely to be somewhat fragile and I don't recommend it, but it's possible.

**Comment by bree-z** [comment]
Thanks @boonebgorges and @beckej13820! We'll discuss and get back to you.

**Comment by bree-z** [comment]
Hi all, 

Thanks for thinking this through! I'm going to cop out and say that I lean towards leaving things as they are since implementing the wp_body_open hook option also doesn't result in a tab order that follows the visual order perfectly. And, as far as I understand it, the custom 'Skip to toolbar' link we have now allows users to navigate to the WP toolbar quickly.

@jennaspevack what do you think?

I also defer to Jenna on the design change option that @beckej13820 raised above:
 
> A third alternative would be to reorder the two rows in the header, and use the current WordPress core behavior, which would make the visual order match the tab order.

(Assuming this would be for a future release, if we want to pursue it.)

Thanks!

**Comment by boonebgorges** [comment]
> I'm going to cop out and say that I lean towards leaving things as they are since implementing the wp_body_open hook option also doesn't result in a tab order that follows the visual order perfectly. And, as far as I understand it, the custom 'Skip to toolbar' link we have now allows users to navigate to the WP toolbar quickly.

I'm going to close the ticket on the basis of this comment.
