### ISSUE TITLE
Template chooser: Interface for changing site association

### ISSUE THREAD

**Issue by boonebgorges** [cuny-academic-commons/commons-in-a-box#400]
It should be possible to select which site a Site Template is associated with.

**Comment by boonebgorges** [comment]
This is built and is ready to test. Here are a few screenshots.

When creating a new Site Template, a message appears letting you know that you can leave the field blank, in which case a new site will be created for you.

![template-site-new](https://user-images.githubusercontent.com/246627/169561332-7889c1be-6101-42ad-8b06-64b0704e122e.png)

When editing an existing Site Template, that message is not visible. Instead, you see the selected Site in the dropdown. You can change the value, but you cannot clear it - Site Templates *must* be associated with a site.

![template-site-edit](https://user-images.githubusercontent.com/246627/169561547-502ded2c-1e3f-4a6b-87e0-5e446994f01e.png)

The dropdown uses Select2 to support AJAX-powered searching. I've opted for the display format `#123 Site Name (http://site-url)` to provide maximal information, but this could be modified if you wish.

![template-site-search](https://user-images.githubusercontent.com/246627/169561699-accb63c0-f8ab-41e5-8c47-6136ae554520.png)

Happy to talk through improvements to this UX.

**Comment by bree-z** [comment]
Thanks Boone! The functionality looks good so far. And, it will be really great to have this!

My main questions are about the UX:

1. Can we adjust the instructions for the dropdown? I was thinking:

Above dropdown: "Below you can select an existing site whose settings and content will be copied to new sites when using this template. If no site is selected, a new site will be created automatically to serve as the template.:

Below dropdown: "To search, [add instructions here]"

This brings me to the next question, since I'm not entirely sure I understand how the dropdown is supposed to work.

1. I'm not sure how to reliably find the correct site. I did it a few times, but then I created the following project to use as a new project template: https://openlabdev.commonsinabox.org/project-site-template-2/  I tried searching by the name, URL, and site ID (using both #541 and just 541), but never found the site. (See gif below.) I finally selected it by typing in "project" and then scrolling all the way down through the list until I saw it. It was a very long list, though I'm not sure that would be the case in a real live installation. Is there anything we could do to improve the UX here?

2. There's something slightly confusing about the dropdown/search (see annotated screenshot below). Not sure there's an easy way to improve this, but if not I think it's OK to leave as is.

3. There was a weird search box that would occasionally pop up in the middle of trying to enter a search term. I'm not sure if this is intended functionality or not. I could dismiss it by pressing esc.

Thanks! (And cc @jennaspevack just in case, though she's mostly off right now.) 

### 1: 

![SearchForTemplateSite](https://user-images.githubusercontent.com/7189824/181621964-1071c7aa-4cbf-4c16-9727-d27ed2a82b33.gif)

### 2: 

<img width="1595" alt="DropdownSearch" src="https://user-images.githubusercontent.com/7189824/181622077-73b3b70d-899d-482c-ad3e-c1e2ee3a047a.png">

### 3: 

<img width="1423" alt="WeirdPopup" src="https://user-images.githubusercontent.com/7189824/181622299-9e16040b-7726-44cb-9462-e286b0f02324.png">

**Comment by boonebgorges** [comment]
Thanks for the feedback, Bree.

>   Can we adjust the instructions for the dropdown? I was thinking:

I've made this change.

>  I'm not sure how to reliably find the correct site. 

It matches based on name or URL. If you search `project-site-template` it narrows down the list as expected. If you're able to reproduce odd non-matching behavior, please provide as many details as possible on how to reproduce. As for the problem of having many dozens of sites called "project template", I think this is an artifact of the test site  and not something we generally need to be worried about, since you can page through results in the dropdown.

> There's something slightly confusing about the dropdown/search (see annotated screenshot below). Not sure there's an easy way to improve this, but if not I think it's OK to leave as is.

This is only happening because you must be opening in a window where the dropdown appears very close to the bottom of the window. In my testing, this only occurs if you have a very short browser window. Can you confirm? 

As a mitigation, I made a change so that when you click the dropdown, the cursor focus is moved to the search field. This should make it clearer that you have to search.

> There was a weird search box that would occasionally pop up in the middle of trying to enter a search term. I'm not sure if this is intended functionality or not. I could dismiss it by pressing esc.

I'm not able to reproduce, nor can I find any indication that this field comes from Select2 or cbox-openlab-core. Maybe it's your browser or OS? If you see it happen again, try to Inspect Element and share some of the markup.

**Comment by bree-z** [comment]
Thanks Boone!

> It matches based on name or URL. If you search project-site-template it narrows down the list as expected. 

Got it, thanks! If I use just 'project-site-template' it works. 

> This is only happening because you must be opening in a window where the dropdown appears very close to the bottom of the window. In my testing, this only occurs if you have a very short browser window. Can you confirm?

The browser window seems to be the issue.

> Maybe it's your browser or OS? If you see it happen again, try to Inspect Element and share some of the markup.

I wasn't able to recreate the weird search box. If it comes up again, I'll share more information. 

> Can we adjust the instructions for the dropdown?

There's an extra line of text at the bottom: "You may select an existing site. If no site is selected, a new site will be created automatically to serve as the template." Could we remove this? Otherwise, it looks good, thanks!

<img width="1442" alt="Screen Shot 2022-07-29 at 1 14 18 PM" src="https://user-images.githubusercontent.com/7189824/181811194-e425e8b5-267c-41b9-9225-c771566fdee3.png">

**Comment by boonebgorges** [comment]
Ah yes, I'd put logic in place that this message should appear only when creating a new template. If you have an existing template, it doesn't apply. As such, I've made a change so that this extra line is removed; furthermore, the second sentence of the help message above the dropdown only appears if you're creating a new template.

**Comment by bree-z** [comment]
Thanks Boone! I no longer see the extra line. And I only see the second sentence above the dropdown when creating a new template.
