### ISSUE TITLE
Toolbar menu items are pushed over to the left side after login

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#409]
Hi Boone, 

When I log into https://openlabdev.commonsinabox.org, the items in the toolbar menu are pushed over all the way to the left. 

Thanks!

<img width="1789" alt="Screen Shot 2022-08-18 at 12 18 42 PM" src="https://user-images.githubusercontent.com/7189824/185458107-d1458064-cc8e-4d21-8be2-52d8c865175d.png">

**Comment by boonebgorges** [comment]
This was caused by the "full width" behavior in https://github.com/cuny-academic-commons/commons-in-a-box/issues/381. I've removed this from the 1.3.x branch.

**Comment by bree-z** [comment]
Thanks, Boone. We were actually hoping to include #381, because the toolbar wrapping onto a second line is something that a number of people have mentioned. It often makes certain things on the Dashboard difficult to access. 

If it's not too difficult to get it working again, that would be great. Thanks!

**Comment by boonebgorges** [comment]
> If it's not too difficult to get it working again, that would be great. Thanks!

It was working, by allowing the toolbar to extend to full-width.

**Comment by bree-z** [comment]
Hi Boone, 

The toolbar is still not aligned correctly (see screenshots of the dev site compared with cboxopenlab.org below). 

And sorry, I'm not sure I understand why extending the toolbar to full-width isn't working now when it was earlier? Is that because of other things we've removed from the 1.3.x branch?

Many thanks!

### openlabdev.commonsinabox.org:

<img width="1237" alt="Screen Shot 2022-08-19 at 11 33 33 AM" src="https://user-images.githubusercontent.com/7189824/185656130-3b56e39c-f87d-4473-84d0-d8d9bd9dc367.png">

### cboxopenlab.org:

<img width="1252" alt="Screen Shot 2022-08-19 at 11 33 39 AM" src="https://user-images.githubusercontent.com/7189824/185656159-1cecd6f6-5650-4e7b-9242-64d6d2e4e80c.png">

**Comment by boonebgorges** [comment]
Sorry, I'm not really clear on the nature of the report in this ticket and how it relates to #381 and to your most recent screenshots.

I've made the following changes. Have a look and let me know whether it seems sufficient for this release. If there are issues, please spell them out in as much detail as you can, so that I can try to thread the needle.

- Reinstated full-width toolbar on subsites
- On the main site, toolbar max-width is 1140px, to match the screenshot from cboxopenlab.org
- On the main site, made a modification so that the 'Hi...' and 'Log Out' links appear at the right

**Comment by bree-z** [comment]
Thanks Boone! And sorry for any confusion. 

Your changes look good. The toolbar alignment looks fine, on the front end and the Dashboard.
