### ISSUE TITLE
Feature Request: Set OpenLab Group Messaging Defaults Sitewide

### ISSUE THREAD

**Issue by beckej13820** [cuny-academic-commons/commons-in-a-box#412]
Description of our problem:

OpenLab sends a lot of emails on heavily used "course hub" type sites where students are all submitting posts to one single website. Although group admins have the ability to change the default settings, doing a review a sites, most admins have left communication settings at the default, and most users have left communication settings as the default, BUT we've still received feedback from instructors and students that they get too many emails from the system.

Request:
I'd like the ability on a network level, to set all new groups that are created on the "daily" email settings as default. I don't need the ability to change all sites settings, I just want the ability to set the default on new sites that are created.

**Comment by boonebgorges** [comment]
Thanks for the ticket. I agree that this might be something for us to consider as an admin-facing option. In the meantime, you can do it via filter in an mu-plugin or elsewhere:

```php
add_filter(
	'ass_default_subscription_level',
	function( $setting ) {
		return 'dig';
	},
	5
);
```

**Comment by boonebgorges** [comment]
We're going to look at this for the 1.5.0 release.

@jennaspevack @bree-z Where would such an option go? When you go to the 'Group Settings' panel, we don't have a place for general settings. https://imgur.com/QetJYyZ.png

**Comment by boonebgorges** [comment]
It dawned on me that this is a feature that should be added directly to BPGES. See https://github.com/boonebgorges/buddypress-group-email-subscription/issues/238. This means that the setting will live in 'Group Email Options', and we have a link to that from the 'Communication Settings' tab.

This is not ready to test yet on openlabdev.commonsinabox.org because it will involve a BPGES update, which I haven't yet done. But here's a screenshot:

![Screenshot_2023-06-07_11-35-13](https://github.com/cuny-academic-commons/commons-in-a-box/assets/246627/a875a6b0-01bc-4889-bf2b-1dc2723adf68)

**Comment by bree-z** [comment]
This makes sense to us, thanks!

**Comment by bree-z** [comment]
This looks good, thanks!
