### ISSUE TITLE
Editing an Academic Term causes order of terms to be reset

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#421]
Hi Boone, 

I'm seeing the issue with Academic Terms being reordered after I edit one of them. It's the same issue noted in the original ticket:

https://github.com/cuny-academic-commons/commons-in-a-box/issues/297#issuecomment-1194544451

Thanks!

**Comment by boonebgorges** [comment]
I'm unable to reproduce. Here are the steps:

1. wp-admin/admin.php?page=cbox-ol-academic-terms, add several items. The page is refreshed each time.
2. Reorder several items, including the newly added items
3. Delete one of the newly added items
4. Manually refresh the page

I'm not seeing any order information being lost.

Could you please verify whether you're seeing the page refresh after you add a new item? If you are, then could you please provide very specific steps to reproduce the error?

**Comment by bree-z** [comment]
Thanks Boone. It seems to be happening inconsistently. Here are a few things I did to reproduce:

1. Edited the term 'Summer I 2020' to become 'Summer 2020'. The page refreshed and the order was reset. 
2. To double check, I went to the Courses directory where after refreshing the page, the dropdown changed to reflect the new order.
3. Added a new term 'Another Term'. The page refreshed, and the order remained the same, with the new term at the top. 
4. Deleted 'New term'. The page refreshed and the order of terms was changed.

I've attached two gifs. The first shows steps 1 and 2. The second shows steps 3 and 4. 

![AcademicTermsOrder](https://user-images.githubusercontent.com/7189824/209567693-905a0858-180a-4d05-b1be-23b8c8691ea7.gif)

![AddThenDeleteTerm](https://user-images.githubusercontent.com/7189824/209567707-7dcd7dae-2745-4c95-aedf-f5e27c9554b1.gif)

**Comment by boonebgorges** [comment]
Thanks for the screenshots. Unfortunately, I'm still not really sure what you are expecting to see vs what you actually see - there's a ton of items on the list and I'm not understanding your intent in both of them.

I have a feeling that the issue here may be the fact that items are given the order '0' when they're first created. This causes a few problems. First, it means that newly-created items end up at the top of the list, a behavior which is probably the opposite of what's generally expected. Second, it means that there could be multiple items with the order '0'. This means that the secondary sort (by 'title') kicks in after refresh, which could be different from the sort that you see before the refresh.

I've put a few additional changes in place:
- When a new term is created, ensure that it ends up last in the list, by finding the order of the last existing term and adding 1
- There's now an enforcement mechanism in place that ensures, on each term save, that each term in the list has its own unique order. This means there can't be multiple with the order of '0'.

Please spend some more time trying to reproduce your issue. It's possible it will now go away. If you still see it, please pare down the number of items in the test environment, and provide more precise details: the items that you create, the order that you saw after creation, any reordering that you did manually, any other changes that you did manually, what you saw after a refresh.

**Comment by bree-z** [comment]
Thanks Boone! I think have some more details. 

> When a new term is created, ensure that it ends up last in the list, by finding the order of the last existing term and adding 1

This part is working for me.

And I can't reproduce the reordering issue in Chrome or Brave, but I can in Firefox and Safari. Here's what I did: 

I deleted some of the existing terms to shorten the list, and added the numbers 1-8 before them, in the order that they appear after they're reordered: 1 Fall 2020, 2 Fall 2021, etc. Then I manually changed the order so that 8 Winter 2023 was at the top and 1 Fall 2020 was at the bottom. I created a new term called 'Another Term' and moved it to the top. I saw a refresh each time I changed the order, and after I created the new term. After manually reordering them this is what I saw:

<img width="2036" alt="AcademicTermsBeforeDelete" src="https://user-images.githubusercontent.com/7189824/209843996-c78bc1cb-721a-4046-85cc-715555245bf3.png">

Then, I deleted 'Another Term'. The page refreshed and the terms had been reset to 1 Fall 2020 at the top, with 8 Winter 2023 at the bottom. Here's a screenshot:

<img width="2045" alt="AcademicTermsAfterDelete" src="https://user-images.githubusercontent.com/7189824/209844553-e409553e-629b-4bf2-9c43-ba5f31ae5067.png">

And here's a gif:

![AcademicTermsFirefox](https://user-images.githubusercontent.com/7189824/209844198-7fa0c9a9-5ec2-484b-a4b9-19f29594dde1.gif)

Then, without changing the order of any terms, I created another new term. The page refreshed. I didn't change anything. Then I deleted the new term. The order stayed the same, with 1 at the top and 8 at the bottom. 

I created another new term, and moved this to the top, while leaving the rest of the terms in order of 1-8 with 1 at the top. I deleted the new term, and the order remained the same.

**Comment by boonebgorges** [comment]
Thanks for the detailed feedback. These instructions helped me to reproduce the problem locally, which in turn allowed me to figure out the root issue.

From what I can see, this is a problem specific to the deletion process. When deleting an item, the JS application attempted to do a reorder to account for the missing item. This reorder depended on certain information being present in the JSON data at the API endpoint. In the case of Academic Terms, the 'order' parameter was not present in this data, with the result that the JS application thought that everything should have order 0. This was causing an alphabetical sort after deletion. I think I have a fix in place that will address it.

**Comment by bree-z** [comment]
Thanks Boone! This looks good. I can't reproduce the reordering issue.
