### ISSUE TITLE
'What's Happening' Feed on the homepage no longer appears in the sidebar

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#451]
Hi Boone, 

The 'What's Happening' Feed no longer appears on the homepage sidebar. It was appearing earlier on in testing, but I'm not sure what changed. When I visit Brand Settings > Home Page > Home Sidebar, I see it there.

It just appeared when I tried a new browser that I hadn't used in a while. I'd also recently cleared the cache. Before logging in, it was there, but disappeared after logging in. I can't get it to reappear, even after logging out and clearing my cache.

Thanks!

<img width="878" alt="WhatsHappening_Dashboard" src="https://github.com/cuny-academic-commons/commons-in-a-box/assets/7189824/6c492aee-70c7-4376-9511-4a59e3ff880d">

**Comment by boonebgorges** [comment]
It's showing up for me:

![Screenshot_2023-07-25_22-24-38](https://github.com/cuny-academic-commons/commons-in-a-box/assets/246627/a7461483-23c4-424b-a83c-f28883a03948)

There's some server-side caching behind this widget. It's possible that the cache was momentarily corrupted. That cache expires every time a new activity item is posted. So it's likely that you created activity since these screenshots were taken, which caused the cache to be regenerated. 

I believe that similar issues have happened occasionally in the history of the OpenLab. Because they've been so infrequent and difficult to reproduce, and because the problem always goes away after the server cache expires, we haven't put much effort into identifying underlying causes. I recommend the same course of (in)action here.

**Comment by bree-z** [comment]
Thanks Boone! This makes sense.
