### ISSUE TITLE
"CBOX OpenLab" section in Dashboard > Menus is missing 

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#459]
Hi Boone - 

I'm noticing that the "CBOX OpenLab" section in Dashboard > Menus added in #195 no longer appears when creating new subsites on two different installations.

I first noticed this on SPS's installation, and I also see the same thing on https://unewhavendh.org/, which is not a new installation. I *cannot* reproduce it on BMCC's OpenLab (but could only test subsites, so I'm not sure what the template sites look like).

On SPS and UNH sites, I don't see the CBOX OpenLab section on template sites or on new subsites. On openlabdev.commonsinabox.org I also don't see the section on template sites, but I do see it on new subsites. 

To test, I created a new template: https://openlabdev.commonsinabox.org/site-template-december-2023-template-1701679258/. The theme was Twenty Twenty Three, so I changed to Twenty Sixteen to check the Dashboard > Menus section.  I created a new Course site using the template: https://openlabdev.commonsinabox.org/december-template-test/ The CBOX OpenLab section does appear on the new course site.

Thanks!

**Comment by boonebgorges** [comment]
The 'CBOX OpenLab' section at Dashboard > Menus was originally built so that it showed only on group sites. Group-type template sites don't technically belong to a group, so they were excluded from this. I've made a change in cc5275f that should fix this for template sites.

But now the 'CBOX OpenLab' section on these template sites is empty. That's because the link that should be there, '[ Project Home ]' (or whatever the group type is), uses data (like URL) from the connected group. In the case of templates, there is no connected group. 

Complicating this is the fact that template sites should, by default, have both a 'Group Home' and a 'Home' link. So, when you go to Dashboard > Appearance > Menus on a site template, you already see a link corresponding to the '[Project Home]' link that you would see under CBOX OpenLab at the left. Now, I can see why you would want to have the ability to add this link *back* if you were to delete it. But it raises questions about the desired workflow.

So can you please think through how you want all of this to work?
- Do you want 'Group Home' and 'Home' links to appear by default on template sites?
- If `[ Project Home ]` appears in Appearance > Menus when viewing a template site, how does that work? When viewing the template site, presumably it will have a dummy link, since there's no "project" to point to. Maybe if this item exists, then maybe during project creation we want to swap out the dummy link with the URL of the newly created project group site?

> On SPS and UNH sites, I don't see the CBOX OpenLab section on template sites or on new subsites.

I can't reproduce the issue with "new subsites". I see the 'CBOX OpenLab' section on regular group sites. For further debugging, I would need access to an installation where I have access to the codebase.

**Comment by bree-z** [comment]
Thanks so much Boone! 

I think your recommendation makes sense.
