### ISSUE TITLE
Issue with CBOX OL site-wide footer in Hamilton theme

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#461]
There’s an issue with the CBOX OL site-wide footer when the [Hamilton](https://wordpress.org/themes/hamilton/) theme is activated, where the footer appears stuck in the middle of the page. See for example: https://unewhavendh.org/math1110/

I'm not sure if I identified the correct thing, but if I remove the 'position: absolute' declaration, the issue goes away:

.oplb-bs#openlab-footer {
position: absolute;
bottom: 0;
right: 0;
left: 0;
}

Thanks!

**Comment by boonebgorges** [comment]
Removing the absolute positioning of the OL footer leaves a bunch of space below the footer on this theme and other themes, and it could also have other knock-on effects that are difficult to predict.

The issue with Hamilton specifically is that it has a declaration along the following lines:

```css
html { height: 100%; }
```

which causes the height of the `<html>` wrapper to be the same as the window height. As such, the OL footer is put just below the initial window height, rather than at the bottom of the document. I don't know why Hamilton does this, and I don't have a straightforward way of working around it within our own CSS without rebuilding the way things work. I've opted in 49a592a for a theme-specific fix that allows the `html` element to have `height: auto;`. It's possible that this will have other effects in Hamilton - as I said, I don't know why they introduced this declaration in the first place - but it seems to fix the problem for me. Perhaps you could test.

**Comment by bree-z** [comment]
Thanks Boone! Hamilton isn't installed on openlabdev.commonsinabox.org so I can't test it there. If it's OK for me to add themes via the Dashboard I can go ahead and do so. Otherwise can you add it when you get a chance?

Thanks!

**Comment by boonebgorges** [comment]
Sure thing. I've installed and network-enabled the theme on openlabdev.commonsinabox.org.

**Comment by bree-z** [comment]
This looks good, thanks!
