### ISSUE TITLE
Remove display name from portfolio directory and portfolio profile

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#479]
Port from the City Tech OpenLab: http://redmine.citytech.cuny.edu/issues/3389

**Comment by boonebgorges** [comment]
This is ready to test on openlabdev.commonsinabox.org.

**Comment by bree-z** [comment]
Thanks, Boone. The display name has been removed from the directory, and 'Member Profile' field no longer appears on the portfolio profile, but there's still a 'Portfolio Contact' field that appears on the portfolio profile. Can we remove this as well? Thanks!

<img width="1310" alt="Screenshot 2024-07-10 at 9 35 35 AM" src="https://github.com/cuny-academic-commons/commons-in-a-box/assets/7189824/3b91c585-31d9-4053-83c5-6a4b1d5a1e72">

**Comment by boonebgorges** [comment]
I've made the change. I've deployed it to openlabdev.commonsinabox.org, but not to your new testing environment - I thought I'd let you do that yourself. Ideally, you'd handle most deployments to your test environment, so that it becomes part of your workflow to pull the latest just before you run a round of testing.

**Comment by bree-z** [comment]
Thanks Boone! I deployed the latest changes to the new testing environment. 

I no longer see the'Portfolio Contact' field.
