### ISSUE TITLE
Ability to apply member profile privacy controls to avatar

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#480]
This would apply the privacy controls ("Who can see this field?") that exist for other fields on the member profile to a member's avatar.

TBD whether this can go into the 1.6.0 milestone.

**Comment by boonebgorges** [comment]
I managed to get a version of this working.

I put the 'Avatar Privacy' controls on the Change Avatar screen. I couldn't think of a better place. I put it inside of a separate "panel" with the heading 'Avatar Privacy'.

Because it's on the Change Avatar screen, it's not feasible to have the same sort of click-to-submit save routine as on the profile edit page. So I've made it save via AJAX. I added some subtle opacity changes to indicate that saving is taking place. IMO this is fairly clear, but if others feel differently, I can probably add some sort of 'Saved' indicator. (So far as I can see, we don't have anything like this elsewhere in CBOX-OL, so I didn't have any prior art.) Moving to a system with an explicit Save button is probably not feasible at this moment, because there are multiple controls on this page that do not work together.

Here is a gif of the control:

![Peek 2024-06-25 09-51](https://github.com/cuny-academic-commons/commons-in-a-box/assets/246627/52bf503e-bcd0-467b-ad8d-74a33091566d)

The settings supported are the same ones that BP offers by default, which are the same ones that CBOX-OL uses. Changing these (how they're named, ordered, etc) is out of scope for the current ticket.

I've done some testing of the avatar privacy protection itself, and it seems to be working in various parts of the CBOX-OL interface. But avatar generation in BuddyPress is complicated, and so various combinations must be tested. Some aspects to consider:

- Check each of the visibility settings (Friends, Only Me, etc). Note that bp_moderate users (ie super admins) can always see avatars, even when set to 'Only Me'.
- Check various interfaces on the main site: user profiles, Members directory, member listing in groups, forum and other interfaces in groups
- Think about places on secondary sites where avatars may be shown. Some themes may use them in comment listings, for example. Check to be sure that they obey privacy settings.
- Test users that have uploaded avatars as well as those with no avatars. Also check those that have not uploaded avatars but who have Gravatars as fallbacks - I'm not 100% sure how this combination will work in all places, or how we might *want* it to work.

**Comment by bree-z** [comment]
I forgot to add one more thing:

When I view a user profile (my own or another user) without an uploaded avatar, I don't see the default CBOX OL avatar. Instead, I see this:

<img width="928" alt="Screenshot 2024-07-11 at 4 14 06 PM" src="https://github.com/cuny-academic-commons/commons-in-a-box/assets/7189824/0abdc97d-2384-4bfe-a0b6-a9024ac4fd2f">


Below is a user profile on openlab.sps.cuny.edu:


<img width="909" alt="Screenshot 2024-07-11 at 4 18 59 PM" src="https://github.com/cuny-academic-commons/commons-in-a-box/assets/7189824/891ca389-6684-49c0-8464-e22f95343412">

**Comment by boonebgorges** [comment]
Avatar treatment throughout the system is very complicated and hard to keep track of. I've just pushed up some changes that seem to make it more consistent. These changes shouldn't affect the visibility aspect of avatars, but they should be tested against different avatar states: no avatar with Gravatar fallback, no avatar without Gravatar fallback (default image), user-uploaded avatar.

**Comment by bree-z** [comment]
Thanks Boone! Avatars appear correctly for the different avatar states. I also did a little more visibility testing and didn't see any issues.
