### ISSUE TITLE
Improve Keyboard Navigation

### ISSUE THREAD

**Issue by bree-z** [cuny-academic-commons/commons-in-a-box#482]
Port from the City Tech OpenLab: http://redmine.citytech.cuny.edu/issues/3307

**Comment by boonebgorges** [comment]
These changes are ready to test on openlabdev.commonsinabox.org.

**Comment by bree-z** [comment]
Thanks Boone. 

I'm not sure if this is related, but there's an issue with the tab order, where when the last item in the footer has focus, the next time I press tab, it skips the 'My Profile' dropdown and instead takes me to the friend requests/invitations icon. This behavior is different from what I see on openlabdev.org, where I go from the footer to the 'My OpenLab' dropdown.

Otherwise the changes look good.

**Comment by boonebgorges** [comment]
In my tests, the next tab after the last item in the footer *does* focus on My Profile, but the menu is not automatically expanded - have to hit Enter to toggle it. This is the same behavior that I see on the City Tech OpenLab. 

One difference I see between the two platforms is that the CT OpenLab has proper outline styling when the 'My OpenLab' toolbar option receives focus. On CBOX-OL, there is no such outline. Indeed, it appears that the outline was disabled on the City Tech OpenLab many years ago, but due to some load-order issues, the `outline:none` declaration wasn't working there, and it's only on CBOX-OL that this "intended" behavior is visible. In any case, it's bad accessibility practice to remove outline styling for focus/active elements, so I've made a change in CBOX-OL to restore it for this specific element. Perhaps this will help to clear up the tab order in your testing.

**Comment by bree-z** [comment]
Yes, this looks good, thanks!
